<?php echo $this->doctype() . "\n";?>
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
<?php echo $this->render('head.phtml') . "\n";?>
 </head>
 <body onload="_onload();" onunload="_onunload();">
  <noscript><h1>Por favor habilite ou use um navegador com suporte a javascript.</h1><h1>Please enable or use a browser that supports javascript.</h1><div style="margin:0 0 9999px 0;"></div></noscript>
  <div id="menubar">
   <div id="menu">
<?php echo $this->render('menu.phtml') . "\n";?>
   </div>
  </div>
  <div id="layout">
   <div id="maincontent">
<?php echo $this->layout()->content; ?>
   </div>
  </div>
  <div id="bottombar"><div id="bottombarback"></div></div>
  <div id="footer">
<?php echo $this->render('footer.phtml') . "\n";?>
  </div>
  <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>
 </body>
</html>
