 <ul id="nav">
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/admin/" onmouseover="return overlib('Go to home page');" onmouseout="return nd();"><span>Home</span></a></li>
  <li class="top"><a class="links top_link" href="javascript:void(0);" onclick="javascript:listbancos()" onmouseover="return overlib('List Bancos');" onmouseout="return nd();"><span>Bancos</span></a></li>
  <li class="top"><a class="links top_link" href="javascript:void(0);" onclick="javascript:listblog()" onmouseover="return overlib('List posts of blog');" onmouseout="return nd();"><span>Blog</span></a></li>
  <li class="top"><a class="links top_link" href="javascript:void(0);" onclick="javascript:listclientes()" onmouseover="return overlib('List clientes');" onmouseout="return nd();"><span>Clientes</span></a></li>
  <li class="top"><a class="links top_link" href="javascript:void(0);" onclick="javascript:listscripts();" onmouseover="return overlib('List scripts');" onmouseout="return nd();"><span>Scripts</span></a></li>
  <li class="top"><a class="links top_link" href="javascript:void(0);" onclick="javascript:listusers()" onmouseover="return overlib('List users');" onmouseout="return nd();"><span>Users</span></a></li>
  <li class="top"><a class="links top_link" href="javascript:void(0);" onclick="javascript:userdetails()" onmouseover="return overlib('Edit Details &amp; Password');" onmouseout="return nd();"><span>My Account</span></a></li>
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/admin/logout" class="top_link" onmouseover="return overlib('Log out the system');" onmouseout="return nd();"><span style='color:#FF0000 !important;'>Logout</span></a></li>
 </ul>
