<?php 
if(count($this->datalist) > 0)
{
	foreach($this->datalist as $dl)
	{
		$cdate = strtotime($dl['cdate']);
		$cdate = date('d/m/Y g:ia', $cdate);
?>
    <div class="menucentertop"></div>
    <div class="menucentermiddle">
     <h1><a href="/blog/<?php echo $dl['url']; ?>.html"><?php echo utf8_encode(stripslashes($dl['title'])); ?></a></h1>
     <p><?php echo utf8_encode(stripslashes($dl['meta_description'])); ?></p>
     <div style='float:right;margin:10px 10px 0 0;font-size:11px;'><?php echo $cdate; ?></div>
    </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>
<?php
	}
	
	if($this->paginator->count() > 1)
	{
		echo "<div class=\"menucenterclear\"></div>\n";
		echo $this->paginationControl($this->paginator, 'Elastic', 'index' . DS . 'pagination.phtml');
		echo "<div class=\"menucenterclear\"></div>\n";
	}
?>
    <div id="pagination">
     <ul id="socialbuttonnav">
      <li><!-- Google plus one--><div><g:plusone size="tall" count="true"></g:plusone></div></li>
      <li><!-- Twitter--><div><a name="twitter_share" data-count="vertical" href="http://twitter.com/share" class="twitter-share-button" >Tweet</a></div></li>
      <li id="fb"><!-- Facebook like--><div id="fb-root"></div><script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script><fb:like href="" send="false" layout="box_count" width="64" show_faces="false" action="like" font=""></fb:like></li>
      <li><!-- linkedin--><div><script type="in/share" data-counter="top"></script></div></li>
      <li><!-- stumbleupon--><div><script src="http://www.stumbleupon.com/hostedbadge.php?s=5"></script></div></li>
      <li><!-- digg--><div><a class="DiggThisButton DiggMedium" href="http://digg.com/submit?url=<?php echo urlencode($_SERVER['SCRIPT_URI']); ?>&amp;title=<?php  ?>"></a></div></li>
      <li><!-- Buzz--><div><a title="Post to Google Buzz" class="google-buzz-button" href="http://www.google.com/buzz/post" data-button-style="normal-count"></a></div></li>
     </ul>
    </div>
    
    <div class="menucentertop"></div>
    <div class="menucentermiddle">
     <h1>Contrate um dos serviços a seguir:</h1>
     <ul>
      <li>Criação do domínio inicial de sua empresa, .com, .com.br, como queira ou necessite</li>
      <li>Um novo site dinâmico em PHP/Mysql para sua empresa pois o atual está obsoleto</li>
      <li>Implementação de E-Commerce com PayPal/Google Checkout</li>
      <li>Hospedagem para o seu site ou de sua empresa</li>
      <li>Montagem de servidores Linux para sua empresa</li>
      <li>Um websistema interno que atenda as necessidades de sua empresa</li>
      <li>Front-End XHTML desenvolvido em Ajax/Javascript/jQuery</li>
     </ul>
     <p><a href="<?php echo SITE_PATH ?>/contato.html">Entre em contato clicando aqui ou clicando no botão "Contato" acima no menu</a></p>
    </div>
    <div class="menucenterbottom"></div>
    <div class="menucenterclear"></div>
<?php
}
?>
