<?php
$this->headTitle()->setSeparator(' - ');
$this->headTitle(SITE_TITLE);
echo $this->headTitle() . "\n";
echo $this->headMeta() . "\n";

$this->headLink()->appendStylesheet(SITE_PATH . '/css/dropdown-front.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/img/skins/tango/skin.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/jquery/jquery.modalbox.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/jquery/jquery.ui.all.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/jquery/jquery-ui-timepicker.css') . "\n";
$this->headLink()->appendStylesheet(SITE_PATH . '/css/jquery/jquery.clock.css') . "\n";
echo $this->headLink() . "\n";

$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery-1.5.1.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.dropdown.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.maskedinput-1.2.2.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.tools.min.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.jcarousel.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.modalbox-1.2.0-min.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery-ui-1.8.11.custom.min.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.ui.datepicker-pt-BR.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.ui.droppable.min.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.ui.mouse.min.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.ui.timepicker.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/jquery/jquery.clock.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/overlib.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . '/js/scripts.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . 'https://apis.google.com/js/plusone.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . 'http://www.google.com/buzz/api/button.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . 'http://platform.twitter.com/widgets.js', 'text/javascript') . "\n";
$this->headScript()->appendFile(SITE_PATH . 'http://platform.linkedin.com/in.js', 'text/javascript') . "\n";
echo $this->headScript() . "\n";
?>
<script type="text/javascript">
(function() {
var s = document.createElement('SCRIPT'), s1 = document.getElementsByTagName('SCRIPT')[0];
s.type = 'text/javascript';
s.async = true;
s.src = 'http://widgets.digg.com/buttons.js';
s1.parentNode.insertBefore(s, s1);
})();

$.clock.locale = {"pt":{
	"weekdays":["Domingo","Segunda-feira","Terça-feira","Quarta-feira","Quinta-feira","Sexta-feira","Sábado"],
	"months":["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"]
}}

$(document).ready(function(){
	$("#twtr-widget-1").css('z-index', '0');
	$("#datetime").clock({"langSet":"pt","format":"24"});
	$("#phone").mask("(99) 9999-9999");
	$("#maincontent").css('left', '15px');
});

function isMobile(){ var index = navigator.appVersion.indexOf("Mobile"); return (index > -1); }
function setStyleMobile(){ document.write('<link rel="stylesheet" href="<?php echo SITE_PATH; ?>/css/mobile.css" />\n'); }
function setStyleRegular(){ document.write('<link rel="stylesheet" href="<?php echo SITE_PATH; ?>/css/site.css" />\n'); }
if(isMobile()){ setStyleMobile(); }else{ setStyleRegular(); }

</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55156063-1', 'auto');
  ga('send', 'pageview');

</script>
  <meta name="google-site-verification" content="UxqypEXHG_9elAmq7ham4v6VlTOlwt-fwaPyGNhR8eo" />
  <link href="<?php echo SITE_PATH; ?>/favicon.ico" rel="shortcut icon" type="image/x-icon" />
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<!--[if IE]>
<style>
#maincontent{left:265px;}
</style>

<![endif]-->