<?php echo $this->doctype() . "\n";?>
<html xmlns="http://www.w3.org/1999/xhtml">
 <head>
<?php echo $this->render('head.phtml') . "\n";?>
 </head>
 <body>
  <noscript><h1>Por favor habilite ou use um navegador com suporte a javascript.</h1><h1>Please enable or use a browser that supports javascript.</h1><div style="margin:0 0 9999px 0;"></div></noscript>
  <div id="topbar">
   <div id="top">
<?php echo $this->render('top.phtml') . "\n";?>
   </div>
  </div>
  <div id="menubar">
   <div id="menu">
<?php echo $this->render('menu.phtml') . "\n";?>
   </div>
  </div>
  <div id="layout">
   <div id="left">
<?php echo $this->render('left.phtml') . "\n";?>
   </div>
   <div id="maincontent">
<?php echo $this->layout()->content; ?>

    <div style="text-align:center;margin:0 auto;">
        <iframe src="http://smartad.mercadolivre.com.br/jm/SmartAd?tool=6112346&creativity=38806&new=N&ovr=N&bgcol=B1B0B0&brdcol=B1B0B0&txtcol=000000&lnkcol=333333&hvrcol=FF0000&prccol=FF0000&word=blog&word=linux&word=informatica&site=MLB" width="468" height="60" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>
    </div>

    <div style="text-align:center;margin:0 auto;">
	<script type="text/javascript"><!--
	google_ad_client = "ca-pub-6309972780716096";
	/* lucianomarinho bottom */
	google_ad_slot = "7747837357";
	google_ad_width = 468;
	google_ad_height = 60;
	//-->
	</script>
	<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
    </div>

   </div>

  </div>
  <div id="bottombar"><div id="bottombarback"></div></div>
  <div id="footer">
<?php echo $this->render('footer.phtml') . "\n";?>
  </div>
  <div id="overDiv" style="position:absolute; visibility:hidden; z-index:1000;"></div>
  <!-- <script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
  <script type="text/javascript">_uacct = "UA-716804-2";urchinTracker();</script> -->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26864262-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
 </body>
</html>
