     <div class="menulefttop"></div>
     <div class="menuleftmiddle">
      <center>
       <a href="http://<?php echo $_SERVER['SERVER_NAME']; ?>" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logo/lucianomarinho-logo-125x125.png" style="border:0;" /></a><br />
       <a href="http://www.linux.com/" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/linux.png" style="border:0;" /></a>
       <a href="http://www.gnu.org/s/bash/" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/pc-sh.png" style="border:0;" /></a><br />
       <a href="http://www.debian.org" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/debian.png" style="border:0;" /></a>
       <a href="http://www.gentoo.org" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/gentoo.png" style="border:0;" /></a>
       <a href="http://www.ubuntu.com" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/ubuntu.png" style="border:0;" /></a><br />
       <a href="http://www.apache.org" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/apache.png" style="border:0;" /></a>
       <a href="http://www.php.net" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/php.png" style="border:0;" /></a>
       <a href="http://www.mysql.com" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/mysql.png" style="border:0;" /></a><br />
       <a href="http://www.w3.org/Style/CSS/" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/css.png" style="border:0;" /></a>
       <a href="http://www.jquery.org" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/jquery.png" style="border:0;" /></a>
       <a href="http://www.w3.org/TR/xhtml2/" target="_blank"><img src="<?php echo SITE_PATH; ?>/img/logos/xhtml.png" style="border:0;" /></a>
      </center>
     </div>
     <div class="menuleftbottom"></div>
     <div class="menuleftclear"></div>

     <div style="float: left;margin:10px 0;padding: 0;position: relative;text-align:center;width: 250px;">
	<iframe src="http://smartad.mercadolivre.com.br/jm/SmartAd?tool=6109429&creativity=40602&new=N&ovr=N&bgcol=B1B0B0&brdcol=B1B0B0&txtcol=000000&lnkcol=333333&hvrcol=FF0000&prccol=FF0000&site=MLB" width="250" height="250" scrolling="no" frameborder="0" marginheight="0" marginwidth="0"></iframe>	 
     </div>
     <div class="menuleftclear"></div>

     <div style="float: left;margin:10px 0;padding: 0;position: relative;text-align:center;width: 250px;">
		<script type="text/javascript"><!--
		google_ad_client = "ca-pub-6309972780716096";
		/* lucianomarinho left */
		google_ad_slot = "2270020836";
		google_ad_width = 160;
		google_ad_height = 600;
		//-->
		</script>
		<script type="text/javascript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js"></script>
     </div>
     <div class="menuleftclear"></div>

    <script src="http://widgets.twimg.com/j/2/widget.js"></script>
    <script>
	/*
new TWTR.Widget({
  version: 2,
  type: 'profile',
  rpp: 4,
  interval: 30000,
  width: 250,
  height: 300,
  theme: {
    shell: {
      background: '#707070',
      color: '#FFFFFF'
    },
    tweets: {
      background: '#EDEEEE',
      color: '#000000',
      links: '#666666'
    }
  },
  features: {
    scrollbar: true,
    loop: false,
    live: true,
    hashtags: true,
    timestamp: true,
    avatars: true,
    behavior: 'all'
  }
}).render().setUser('nickmarinho').start();
	*/
    </script>
