 <ul id="nav">
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/" onmouseover="return overlib('Página Inicial');" onmouseout="return nd();"><span>Home</span></a></li>
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/portfolio.html" onmouseover="return overlib('Portfólio de clientes');" onmouseout="return nd();"><span>Portfólio</span></a></li>
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/scripts.html" onmouseover="return overlib('Html, jQuery, PHP, Shell, etc...');" onmouseout="return nd();"><span>Scripts</span></a></li>
  <li class="top"><a class="links top_link" href="<?php echo SITE_PATH; ?>/contato.html" onmouseover="return overlib('Entre em contato comigo');" onmouseout="return nd();"><span>Contato</span></a></li>
 </ul>
