<div id="topleft">
 <a href="<?php echo SITE_PATH; ?>/" onmouseover="return overlib('Ir para página inicial do site');" onmouseout="return nd();">
  <div id="toplogotop"></div>
  <div id="toplogobottom"></div>
 </a>
</div>
<div id="topright">
 <div class="toprightsi">
  <center>
   <a href="/rss.html" onmouseover="return overlib('Siga meu site a partir do RSS Reader');" onmouseout="return nd();"><img src="<?php echo SITE_PATH; ?>/img/si/rss.png" /></a>
   <a target="_blank" href="http://twitter.com/#!/nickmarinho/" onmouseover="return overlib('Siga-me no twitter');" onmouseout="return nd();"><img src="<?php echo SITE_PATH; ?>/img/si/twitter.png" /></a>
   <a target="_blank" href="http://www.facebook.com/profile.php?id=100001714905757" onmouseover="return overlib('Siga-me no Facebook');" onmouseout="return nd();"><img src="<?php echo SITE_PATH; ?>/img/si/facebook.png" /></a>
   <a target="_blank" href="https://profiles.google.com/115328546541407589557" onmouseover="return overlib('Adicione-me ao seu Google Plus');" onmouseout="return nd();"><img src="<?php echo SITE_PATH; ?>/img/si/plusone.png" /></a>
  </center>
 </div>
 <div id="datetime"></div>
</div>