<?php
$row = $this->row;
$id_cliente = $this->id_cliente;
$valor = number_format($row['valor'],2,',','.');
$vencimento = date("d/m/Y", strtotime($row['vencimento']));
?>
  <td id='td_<?php echo $this->div; ?>' colspan='8' style='width:944px;'>
Valor: <input type='text' name='valornew_<?php echo $row['id']; ?>' id='valornew_<?php echo $row['id']; ?>' value='<?php echo $valor; ?>' onkeypress='javascript:updateboletos("<?php echo $id_cliente; ?>","<?php echo $row['id']; ?>", "<?php echo $this->div; ?>", event);' size='10' /><input type='hidden' name='id' id='id' value='<?php echo $row['id']; ?>' /> 
Vencimento: <input type='text' name='vencimentonew_<?php echo $row['id']; ?>' id='vencimentonew_<?php echo $row['id']; ?>' value='<?php echo $vencimento; ?>' onkeypress='javascript:updateboletos("<?php echo $id_cliente; ?>","<?php echo $row['id']; ?>", "<?php echo $this->div; ?>", event);' size='12' /> 
Mês Ref.: <input type='text' name='mesrefnew_<?php echo $row['id']; ?>' id='mesrefnew_<?php echo $row['id']; ?>' value='<?php echo $row['mes_referencia']; ?>' onkeypress='javascript:updateboletos("<?php echo $id_cliente; ?>","<?php echo $row['id']; ?>", "<?php echo $this->div; ?>", event);' size='7' /> 
N&uacute;mero: <input type='text' name='numeronew_<?php echo $row['id']; ?>' id='numeronew_<?php echo $row['id']; ?>' value='<?php echo $row['numero']; ?>' onkeypress='javascript:updateboletos("<?php echo $id_cliente; ?>","<?php echo $row['id']; ?>", "<?php echo $this->div; ?>", event);' size='10' /> 
Obs: <input type='text' name='obsnew_<?php echo $row['id']; ?>' id='obsnew_<?php echo $row['id']; ?>' value='<?php echo $row['obs']; ?>' size='85' /> 
<a class='button' onclick='updatemboletos("<?php echo $id_cliente; ?>","<?php echo $row['id']; ?>","<?php echo $this->div; ?>");'>Ok</a> 
<a class='button' onclick="canceledit('<?php echo $row['id']; ?>','<?php echo $this->div; ?>','boletos');">Cancel</a>
<input type='hidden' name='id_cliente_<?php echo $row['id']; ?>' id='id_cliente_<?php echo $row['id']; ?>' value='<?php echo $row['id_cliente']; ?>' />
<script type='text/javascript'>
loff();
$("#vencimentonew_<?php echo $row['id']; ?>").mask("99/99/9999");
$("#mesrefnew_<?php echo $row['id']; ?>").mask("99/9999");
$("#valornew_<?php echo $row['id']; ?>").maskMoney({symbol:"R$ ", showSymbol:false, thousands:".", decimal:",", symbolStay: true});
$("#valornew_<?php echo $row['id']; ?>").focus().select();
$(".button").button();
</script>
  </td>
  <td style='text-align:center;width:19px;'><img src='<?php echo SITE_PATH; ?>/img/admin/delete.png' style='border:0px;cursor:pointer;' onclick="removeboletos('<?php echo $id_cliente; ?>','<?php echo $row['id']; ?>', '<?php echo $this->div; ?>');" title="Deletar <?php echo $row['id']; ?>" /></td>
