<?php $row = $this->row; ?>
  <td id='td_<?php echo $this->div; ?>' style='cursor:pointer;width:944px;'><?php echo utf8_encode(stripslashes($row['name'])); ?></td>
  <td style='text-align:center;width:19px;'><img src='<?php echo SITE_PATH; ?>/img/admin/edit.png' class='img' onclick="editscriptscategories('<?php echo $row['id']; ?>', '<?php echo $this->div; ?>');" title="Editar <?php echo $row['id']; ?>" /></td>
  <td style='text-align:center;width:19px;'><img src='<?php echo SITE_PATH; ?>/img/admin/delete.png' class='img' onclick="removescriptscategories('<?php echo $row['id']; ?>', '<?php echo $this->div; ?>');" title="Deletar <?php echo $row['id']; ?>" /></td>
  