<?php
$pagename = $this->pagename;
$user = $this->user;
$name = $this->name;
$email = $this->email;
echo "<script>newfieldcount = " . count($this->datalist) . ";loff();nd();</script>\n";
?>
<br />
<table class='sample' align='center'>
 <tbody>
  <tr>
   <td style="text-align:left;width:25%;">
    <!-- <a class="button" onclick="javascript:scriptsadd();">Add New</a> -->
    <a class="button openmodalbox" onclick="javascript:void(0);">Add New<input type="hidden" name="ajaxhref" value="addusers" /></a>
   </td>
   <td style="text-align:center;width:80%;">
    Filter: <input type="text" id="fuser" name="fuser" value="" onkeypress="javascript:filter('users',event);" size="30" />
    <input type="text" id="fname" name="fname" value="" onkeypress="javascript:filter('users',event);" size="30" />
    <input type="text" id="femail" name="femail" value="" onkeypress="javascript:filter('users',event);" size="30" />
    <a class="button" onclick="filterm('users');">Ok</a>
   </td>
  </tr>
 </tbody>
</table>

<table class='sample' align='center' id="grid">
 <thead>
  <tr>
   <th style='width:165px;'>User</th>
   <th style='width:350px;'>Name</th>
   <th style='width:341px;'>Email</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
  </tr>
 </thead>
 <tbody id="list">
<?php
if(count($this->datalist) > 0)
{
	$c = 0;
	foreach ($this->datalist as $data)
	{
		$over = "overa";
?>
 <tr id='list_<?php echo $c; ?>' class="<?php echo $over; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $over; ?>'">
  <td style='width:165px;'><?php
if(!empty($user)) echo str_ireplace($user, "<b class='filterwords'>" . $user . "</b>", utf8_encode(stripslashes($data['user']))); 
else echo utf8_encode(stripslashes($data['user']));
?></td>
  <td id='td_<?php echo $c; ?>' style='width:350px;'><?php
if(!empty($name)) echo str_ireplace($name, "<b class='filterwords'>" . $name . "</b>", utf8_encode(stripslashes($data['name']))); 
else echo utf8_encode(stripslashes($data['name']));
?></td>
  <td id='td_<?php echo $c; ?>' style='width:341px;'><?php
if(!empty($email)) echo str_ireplace($email, "<b class='filterwords'>" . $email . "</b>", utf8_encode(stripslashes($data['email']))); 
else echo utf8_encode(stripslashes($data['email']));
?></td>
  <td style='text-align:center;width:19px;' id="activeonoff_<?php echo $data['id']; ?>">
   <a onclick="javascript:activeonoff('users','<?php echo $data['id']; ?>','<?php echo $c; ?>');" onmouseover="return overlib('Active OnOff ID: <?php echo $data['id']; ?>');" onmouseout="return nd();">
    <img src='<?php echo SITE_PATH; ?>/img/admin/<?php if($data['active'] == '1'){ echo 'ok.png'; } else{ echo 'not-ok.png'; } ?>' class='img' />
   </a>
  </td>
  <td style='text-align:center;width:19px;'>
   <a class="openmodalbox" onclick="javascript:void(0);" onmouseover="return overlib('Edit ID: <?php echo $data['id']; ?>');" onmouseout="return nd();">
    <img src='<?php echo SITE_PATH; ?>/img/admin/edit.png' class='img' />
    <input type="hidden" name="ajaxhref" value="editusers?id=<?php echo $data['id']; ?>" />
   </a>
  </td>
  <td style='text-align:center;width:19px;'>
   <img src='<?php echo SITE_PATH; ?>/img/admin/delete.png' class='img' onclick="removeusers('<?php echo $data['id']; ?>','<?php echo $c; ?>');" title="Remove ID: <?php echo $data['id']; ?>" onmouseover="return overlib('Remove <?php echo $data['id']; ?>');" onmouseout="return nd();" />
  </td>
 </tr>
<?php
		$c++;
	}
}
else
{
?>
 <tr id="list_empty" class="<?php echo $dcolors[$d]; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $dcolors[$d]; ?>'">
  <td colspan='7' style='text-align:center;'><a class="button openmodalbox" onclick="javascript:void(0);">Nothing in database, click here to add<input type="hidden" name="ajaxhref" value="addusers" /></a></td>
 </tr>
<?php
 } ?>
 </tbody>
</table>

<div id="paginationdiv">
<?php 
if($this->paginator->count() > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'admin' . DS . 'pagination.phtml');
?>
</div>
