<?php
$pagename = $this->pagename;
$name = $this->name;
echo "<script>newfieldcount = " . count($this->datalist) . ";loff();nd();</script>\n";
?>
<br />
<table class='sample' align='center'>
 <tbody>
  <tr>
   <td style="text-align:left;width:25%;">
    <a class="button" onclick="javascript:addscriptscategories();">Add New</a>
    <a class="button" onclick="javascript:listscripts();">List Scripts</a>
   </td>
   <td style="text-align:center;">
    Filter By Name: <input type="text" id="fname" name="fname" value="" onkeypress="javascript:filter('scriptscategories',event);" size="50" />
    <a class="button" onclick="filterm('scriptscategories');">Ok</a>
   </td>
  </tr>
 </tbody>
</table>

<table class='sample' align='center' id="grid">
 <thead>
  <tr>
   <th style='width:925px;'>Name</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
  </tr>
 </thead>
 <tbody id="list">
<?php
if(count($this->datalist) > 0)
{
	$c = 0;
	foreach ($this->datalist as $data)
	{
		$over = "overa";
?>
 <tr id='list_<?php echo $c; ?>' class="<?php echo $over; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $over; ?>'">
  <td id='td_<?php echo $c; ?>' style='cursor:pointer;width:925px;' onclick="javascript:editscriptscategories('<?php echo $data['id']; ?>', '<?php echo $c; ?>');"><?php
if(!empty($name)) echo str_ireplace($name, "<b class='filterwords'>" . $name . "</b>", utf8_encode(stripslashes($data['name']))); 
else echo utf8_encode(stripslashes($data['name']));
?></td>
  <td style='text-align:center;width:19px;'><img src='<?php echo SITE_PATH; ?>/img/admin/edit.png' class='img' onclick="editscriptscategories('<?php echo $data['id']; ?>','<?php echo $c; ?>');" onmouseover="return overlib('Editar ID: <?php echo $data['id']; ?>');" onmouseout="return nd();" /></td>
  <td style='text-align:center;width:19px;'><img src='<?php echo SITE_PATH; ?>/img/admin/delete.png' class='img' onclick="removescriptscategories('<?php echo $data['id']; ?>','<?php echo $c; ?>');" onmouseover="return overlib('Deletar ID: <?php echo $data['id']; ?>');" onmouseout="return nd();" /></td>
 </tr>
<?php
		$c++;
	}
}
else
{
?>
 <tr id="list_empty" class="<?php echo $dcolors[$d]; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $dcolors[$d]; ?>'">
  <td colspan='7' style='text-align:center;'><a class="button" onclick='addscriptscategories();'>Nothing in database, click here to add</a></td>
 </tr>
<?php
 } ?>
 </tbody>
</table>

<div id="paginationdiv">
<?php 
if($this->paginator->count() > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'admin' . DS . 'pagination.phtml');
?>
</div>
