<?php
$pagename = $this->pagename;
$nome = $this->nome;
echo "<script>newfieldcount = " . count($this->datalist) . ";loff();nd();</script>\n";
?>
<br />
<table class='sample' align='center'>
 <tbody>
  <tr>
   <td style="text-align:left;width:25%;"><a class="button openmodalbox" onclick="javascript:void(0);">Add New<input type="hidden" name="ajaxhref" value="addclientes" /></a></td>
   <td style="text-align:center;width:80%;">
    Filter: <input type="text" id="fnome" name="fnome" value="" onkeypress="javascript:filter('clientes',event);" size="45" />
    <input type="text" id="femail" name="femail" value="" onkeypress="javascript:filter('clientes',event);" size="45" />
    <input type="text" id="fcpfcnpj" name="fcpfcnpj" value="" onkeypress="javascript:filter('clientes',event);" size="45" />
    <a class="button" onclick="filterm('clientes');">Ok</a>
   </td>
  </tr>
 </tbody>
</table>

<table class='sample' align='center' id="grid">
 <thead>
  <tr>
   <th style='width:797px;'>Name</th>
   <th style='width:140px;'>Cpf/Cnpj</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
   <th style='width:19px;'>&nbsp;</th>
  </tr>
 </thead>
 <tbody id="list">
<?php
if(count($this->datalist) > 0)
{
	$c = 0;
	foreach ($this->datalist as $data)
	{
		if($data['ativo'] == '1'){ $over = "overa"; }
		else{ $over = "overb"; }
?>
 <tr id='list_<?php echo $c; ?>' class="<?php echo $over; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $over; ?>'">
  <td style='width:797px;'><?php 
if(!empty($nome)) echo str_ireplace($nome, "<b class='filterwords'>" . $nome . "</b>", utf8_encode(stripslashes($data['nome']))); 
else echo utf8_encode(stripslashes($data['nome']));
?></td>
  <td style='width:137px;'><?php echo $data['cpfcnpj']; ?></td>
  <td style='text-align:center;width:19px;'>
   <a onclick="javascript:listboleto('<?php echo $data['id']; ?>');" onmouseover="return overlib('Listar Boletos ID: <?php echo $data['id']; ?>');" onmouseout="return nd();">
    <img src='<?php echo SITE_PATH; ?>/img/admin/boletos.jpg' style='border:1px solid #000;cursor:pointer;width:14px;' />
   </a>
  </td>
  <td style='text-align:center;width:19px;' id="activeonoff_<?php echo $data['id']; ?>">
   <a onclick="javascript:activeonoff('clientes','<?php echo $data['id']; ?>','<?php echo $c; ?>');" onmouseover="return overlib('Active Display ID: <?php echo $data['id']; ?>');" onmouseout="return nd();">
    <img src='<?php echo SITE_PATH; ?>/img/admin/<?php if($data['ativo'] == '1'){ echo 'ok.png'; } else{ echo 'not-ok.png'; } ?>' class='img' />
   </a>
  </td>
  <td style='text-align:center;width:19px;'>
   <a class="openmodalbox" onclick="javascript:void(0);" onmouseover="return overlib('Edit ID: <?php echo $data['id']; ?>');" onmouseout="return nd();">
    <img src='<?php echo SITE_PATH; ?>/img/admin/edit.png' class='img' />
    <input type="hidden" name="ajaxhref" value="editclientes?id=<?php echo $data['id']; ?>" />
   </a>
  </td>
  <td style='text-align:center;width:19px;'>
   <img src='<?php echo SITE_PATH; ?>/img/admin/delete.png' class='img' onclick="removeclientes('<?php echo $data['id']; ?>','<?php echo $c; ?>');" title="Remove ID: <?php echo $data['id']; ?>" onmouseover="return overlib('Remove <?php echo $data['id']; ?>');" onmouseout="return nd();" />
  </td>
 </tr>
<?php
		$c++;
	}
}
else
{
?>
 <tr id="list_empty" class="<?php echo $dcolors[$d]; ?>" onmouseover="this.className='over'" onmouseout="this.className='<?php echo $dcolors[$d]; ?>'">
  <td colspan='7' style='text-align:center;'><a class="button openmodalbox" onclick="javascript:void(0);">Nothing in database, click here to add<input type="hidden" name="ajaxhref" value="addblog" /></a></td>
 </tr>
<?php
 } ?>
 </tbody>
</table>

<div id="paginationdiv">
<?php
if($this->paginator->count() > 1) echo $this->paginationControl($this->paginator, 'Elastic', 'admin' . DS . 'pagination.phtml');
?>
</div>
