<script type="text/javascript">
var bcpfcnpj = ''; var bemail = ''; var bid_cliente = ''; var bname = ''; var bnome = ''; var btitle = ''; var buser = '';
<?php 
if(!empty($_SESSION['cpfcnpj'])) echo "cpfcnpj = '" . $_SESSION['cpfcnpj'] . "';\n";
if(!empty($_SESSION['email'])) echo "bemail = '" . $_SESSION['email'] . "';\n";
if(!empty($_SESSION['id_cliente'])) echo "bid_cliente = '" . $_SESSION['id_cliente'] . "';\n";
if(!empty($_SESSION['name'])) echo "bname = '" . $_SESSION['name'] . "';\n";
if(!empty($_SESSION['nome'])) echo "bnome = '" . $_SESSION['nome'] . "';\n";
if(!empty($_SESSION['title'])) echo "btitle = '" . $_SESSION['title'] . "';\n";
if(!empty($_SESSION['user'])) echo "buser = '" . $_SESSION['user'] . "';\n";
?>
</script>
<table class='sample' align='center'>
 <tbody>
  <tr>
   <td style="text-align:center;">
   
<!-- First page link -->
<?php
if(isset($this->previous))
{
?>
<span class="previous"><a class="links button" href="javascript:void(0);" onclick="list<?php echo $_SESSION['pagename'] . "('" . $this->first . "', bcpfcnpj, bemail, bid_cliente, bname, bnome, btitle, buser);"; ?>" title="First Page">|&laquo;</a></span>
<?php 
}
else
{
?>
<span class="previous-off button">|&laquo;</span>
<?php 
}
?>

<!-- Previous page link -->
<?php
if (isset($this->previous))
{
?>
<span class="previous"><a class="links button" href="javascript:void(0);" onclick="list<?php echo $_SESSION['pagename'] . "('" . $this->previous . "', bcpfcnpj, bemail, bid_cliente, bname, bnome, btitle, buser);"; ?>" title="Previous Page">&laquo;</a></span>
<?php 
}
else
{
?>
<span class="previous-off button">&laquo;</span>
<?php 
}
?>

<!-- Numbered page links -->
<?php 
foreach ($this->pagesInRange as $page)
{
	if ($page != $this->current)
	{	
?>
<a class="links button" href="javascript:void(0);" onclick="list<?php echo $_SESSION['pagename'] . "('" . $page . "', bcpfcnpj, bemail, bid_cliente, bname, bnome, btitle, buser);"; ?>" title="Go to page '<?php echo $page; ?>'"><?php echo $page; ?></a>
<?php 
	}
	else
	{
?>
<span class="active button"><?php echo $page . " "; ?></span>
<?php 
	}
}
?>

<!-- Next page link -->
<?php
if (isset($this->next))
{
?>
<span class="next"><a class="links button" href="javascript:void(0);" onclick="list<?php echo $_SESSION['pagename'] . "('" . $this->next . "', bcpfcnpj, bemail, bid_cliente, bname, bnome, btitle, buser);"; ?>" title="Next Page">&raquo;</a></span>
<?php 
}
else
{
?>

<span class="next-off button">&raquo;</span>
<?php 
}
?>

<!-- Last page link -->
<?php
if (isset($this->next))
{
?>
<span class="next"><a class="links button" href="javascript:void(0);" onclick="list<?php echo $_SESSION['pagename'] . "('" . $this->last . "', bcpfcnpj, bemail, bid_cliente, bname, bnome, btitle, buser);"; ?>" title="Last Page">&raquo;|</a></span>
<?php 
}
else
{
?>
<span class="next-off button">&raquo;|</span>
<?php 
}
?>
   </td>
  </tr>
  <tr>
   <td style="text-align:center;"><span class="previous-off button">Página <?php echo $this->current; ?> de <?php echo $this->last; ?></span></td>
  </tr>
 </tbody>
</table>
